// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoyalVilla_API.Context;

#nullable disable

namespace RoyalVilla_API.Migrations
{
    [DbContext(typeof(RoyalVilleDbContext))]
    partial class RoyalVilleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoyalVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxurious villa with stunning ocean views and a private beach access.",
                            ImageUrl = "https://media.istockphoto.com/id/506903162/photo/luxurious-villa-with-pool.jpg?s=612x612&w=0&k=20&c=Ek2P0DQ9nHQero4m9mdDyCVMVq3TLnXigxNPcZbgX2E=",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Rate = 500.0,
                            Sqft = 2500,
                            UpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxurious palace with stunning ocean views and a private beach access.",
                            ImageUrl = "https://media.istockphoto.com/id/165824154/photo/emirates-palace-abu-dhabi-uae.jpg?s=612x612&w=0&k=20&c=vmOX2eZZwJp1hy1pPsWqs5V6Mc9ZN-LKfgoHvgn1w-8=",
                            Name = "Royal Palace",
                            Occupancy = 14,
                            Rate = 800.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxurious mansion with stunning ocean views.",
                            ImageUrl = "https://img.freepik.com/free-photo/colonial-style-house-night-scene_1150-17925.jpg?semt=ais_rp_progressive&w=740&q=80",
                            Name = "Mansion",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 1500
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "shark house under reconstruction with stunning ocean views and a private beach access.",
                            ImageUrl = "https://cdn2.tuoitre.vn/thumb_w/750/471584752817336320/2025/7/15/shark1-1752548161011780290376-44-0-800-1210-crop-17525481761621830934074.png",
                            Name = "shark",
                            Occupancy = 2,
                            Rate = 100.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
